name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python - <<'PY'
          import importlib.util
          assert importlib.util.find_spec('flask')
          import app  # ensure app imports cleanly
          print("import OK")
        PY
